### ISSUE TITLE
Espoo data needs to be updated

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/rytj#2]
Bug in database: tietoyksikko needs to be linked to kaavamaarays-table, not to kaavakohde-table.

**Comment by rekjuh** [comment]
Cause of issue:
When adding items to "tietoyksikko" via attribute table, field "id_kaavamaarays"  is not visible by default.
Solution:
Added "id_kaavamaarays" field for "tietoyksikko" layer on Layer properties > Attribute Form. Display expression (for now):
'kaavamaarays: ' ||   "id_kaavamaarays_laji_ak" || ' kohde: ' || "id_kaavakohde" (Preview: 'kaavamaarays: 134 kohde: 13'

**Comment by rekjuh** [comment]
Data fixed on 23.2.
